### ISSUE TITLE
wp upcoming releases plugin

### ISSUE THREAD

**Issue by abizerraj** [HenriqueSilverio/wp-upcoming-releases#8]
Nothing new for now, stay tuned. How long does it take the plugin to show new releases?

**Comment by HenriqueSilverio** [comment]
Hi @abizerraj, have you registered your items through the ["Releases" > "New Release"](https://raw.githubusercontent.com/HenriqueSilverio/wp-upcoming-releases/master/screenshots/screenshot-4.png) menu?

**Comment by abizerraj** [comment]
No

Abizer Raj



On May 21, 2019, at 9:32 PM, Henrique Silvério <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @abizerraj<https://github.com/abizerraj>, have you registered your items through the "Releases" > "New Release"<https://raw.githubusercontent.com/HenriqueSilverio/wp-upcoming-releases/master/screenshots/screenshot-4.png> menu?

**Comment by HenriqueSilverio** [comment]
@abizerraj Go to "Releases" > "New Release" menu, and add some items to be shown in your site.

**Comment by abizerraj** [comment]
Thanks but we were looking for something that can add movies automatically.

Abizer Raj



On May 21, 2019, at 9:38 PM, Henrique Silvério <notifications@github.com<mailto:notifications@github.com>> wrote:


@abizerraj<https://github.com/abizerraj> Go to "Releases" > "New Release" menu, and add some items to be shown in your site.
